export const RECEIVE_USERINFO = 'receive_userinfo'
export const RECEIVE_USERID = 'receive_userid'
export const RECEIVE_IMAGE_INFOS = 'receive_image_infos'
export const RECEIVE_BLOG_INFOS = 'receive_blog_infos'
export const RECEIVE_BLOG_ID = 'receive_blog_id'
